require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "*.gemspec"

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - "examples/**/*.rb"
    - "spec/**/*.rb"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/*-*.rb"

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ObjectThen:
  Enabled: false

Style/RedundantStructKeywordInit:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StructInheritance:
  Enabled: false
