name: release

on:
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.4"
      - run: |
          mkdir -p ~/.gem && touch ~/.gem/credentials && chmod 0600 ~/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${API_KEY}\n" > ~/.gem/credentials
          bundle install
          bundle exec rake push
        env:
          API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
